### ISSUE TITLE
CompositeRequest

### ISSUE THREAD

**Issue by a-a-k** [Xambey/DaData.ApiClient#10]
Как предполагается использовать `CompositeRequest`, а именно чем заполнять значения `Structure ` и `Data`? Просто плоским JSON в виде строки или есть какие-то обёртки?

**Comment by Xambey** [comment]
Я честно говоря уже плохо помню, но если каких-то полей внутри не хватает, предлагаю вам их добавить, поправить соответствующие тесты и сделать pull request, который я с удовольствием приму и выпущу новую версию клиента

**Comment by Xambey** [comment]
Вот пример:

``` json
{
  "structure": [
    "AS_IS",
    "NAME",
    "ADDRESS",
    "PHONE"
  ],
  "data": [
    [
      "1",
      "Федотов Алексей",
      "Москва, Сухонская улица, 11 кв 89",
      "8 916 823 3454"
    ],
    [
      [
        "2"
      ],
      [
        "Иванов",
        "Сергей Владимирович"
      ],
      [
        "мск",
        "улица свободы",
        "65",
        "12"
      ],
      [
        "495 663-12-53"
      ]
    ],
    [
      "3",
      [
        "Ольга Павловна",
        "Ященко"
      ],
      [
        "",
        "Спб, ул Петрозаводская 8",
        "",
        ""
      ],
      "457 07 25"
    ]
  ]
}
```

С этим методом была проблема, в новой выпущенной версии это проблема исправлена
