### ISSUE TITLE
Запрос на остаток за день по сервису Подсказок

### ISSUE THREAD

**Issue by o4zloiroman** [Xambey/DaData.ApiClient#11]
Я не вижу, или его библиотека не поддерживает?

**Comment by Xambey** [comment]
я знаю только один метод для того, чтобы узнать баланс https://dadata.ru/api/balance/

**Comment by o4zloiroman** [comment]
Там еще вот такой есть https://dadata.ru/api/stat/, и по нему можно подсчитать сколько осталось доступных за день запросов в Подсказки.

**Comment by Xambey** [comment]
Хз, я не помню если честно, вроде он не добавлялся. У меня на добавление нового ф-ционала времени не хватает, если вам это необходимо, предлагаю добавить вам этот новый метод и тест для него в pull request, я выпущу новую версию как только смогу протестить

**Comment by Xambey** [comment]
Добавлено в версии 1.1.50
