### ISSUE TITLE
В каком случае UserBalanceResponse.Balance может быть null?

### ISSUE THREAD

**Issue by makrushin-evgenii** [Xambey/DaData.ApiClient#13]
https://github.com/Xambey/DaData.ApiClient/blob/cbab92a8e6b26d671e91c6c1d4ca5afb452ebb85/Dadata/Models/Additional/Responses/UserBalanceResponse.cs#L5

Судя по тестам, поле не должно принимать значение `null` вообще:
https://github.com/Xambey/DaData.ApiClient/blob/3a7f55a9bb917c4b8622897e368c763ef99d0a1a/Dadata.Test/AdditionalApi.cs#L155-L160

Как правильно обработать ответ при `!UserBalanceResponse.Balance.HasValue`?

**Comment by Xambey** [comment]
Исправлено в 1.1.51
