### ISSUE TITLE
Inapropriate data model DaData.Models.Additional.Data.DataOrganization

### ISSUE THREAD

**Issue by amphasis** [Xambey/DaData.ApiClient#3]
The model contains following properties
```
List<DataAuthority> Authorities
List<DataDocument> Documents
```
According to [DaData documentation](https://dadata.ru/api/find-party/#request) those types should be IDictionary<string, DataAuthority>,  IDictionary<string, DataDocument> or plain objects like
```
public class DataAuthorities
{
    public DataAuthority FtsRegistration { get; set; }
    public DataAuthority FtsReport { get; set; }
    public DataAuthority Pf { get; set; }
    public DataAuthority Sif { get; set; }
}

public class DataDocuments
{
    public DataDocument FtsRegistration { get; set; }
    public DataDocument PfRegistration { get; set; }
    public DataDocument SifRegistration { get; set; }
}
```

**Comment by Xambey** [comment]
Thanks for the info, if it doesn't bother you, can you make a pull request with edits?  I am not an employee of the company and lately I dont follow changes in api, therefore your help is very relevant
